DEFAULT_SPRITE_SIZE = 64
SPRITE_SIZE = 48

BLOCK_SIZE = 48
BLOCK_HEIGHT = 48
BLOCK_WIDTH = 48
BLOCK_RESOURCE_SIZE = 48
BLOCK_RESOURCE_HEIGHT = 48
BLOCK_RESOURCE_WIDTH = 48

MOVEABLE_SIZE = 48
MOVEABLE_HEIGHT = 48
MOVEABLE_WIDTH = 48
MOVEABLE_RESOURCE_SIZE = 48
MOVEABLE_RESOURCE_HEIGHT = 48
MOVEABLE_RESOURCE_WIDTH = 48

BLOCK_COUNT_HORIZONTAL = 17
BLOCK_COUNT_VERTICAL = 13

WINDOW_WIDTH = BLOCK_COUNT_HORIZONTAL * SPRITE_SIZE
WINDOW_HEIGHT = BLOCK_COUNT_VERTICAL * SPRITE_SIZE

BRICK_SPAWN_CHANCE = .8
ENEMY_SPAWN_CHANCE = .1
ENEMY_COUNT = 5

GAME_SPEED = 60
PLAYER_SPEED = 2
ENEMY_SPEED = 1

RESPAWN_TIME = 3

EMPTY = 0
RESERVED = 1
GRASS = 2
WALL = 3
BRICK = 4
PLAYER = 5
ENEMY = 6
BOMB = 7

TEMPLATE_EMPTY = '/'
TEMPLATE_RESERVED = 'R'
TEMPLATE_WALL = 'W'
TEMPLATE_BLOCK = 'B'
TEMPLATE_PLAYER = 'P'
