DEFAULT_RESOURCE_SIZE = 64
RESOURCE_SIZE = 48
SPRITE_SIZE = RESOURCE_SIZE

PIXMAP_SIZE = SPRITE_SIZE
PIXMAP_RESOURCE_HEIGHT = PIXMAP_SIZE
PIXMAP_RESOURCE_WIDTH = PIXMAP_SIZE

MOVIE_SIZE = SPRITE_SIZE
MOVIE_HEIGHT = MOVIE_SIZE
MOVIE_WIDTH = MOVIE_SIZE

STATIC_SIZE = SPRITE_SIZE
STATIC_HEIGHT = STATIC_SIZE
STATIC_WIDTH = STATIC_SIZE

DYNAMIC_SIZE = SPRITE_SIZE
DYNAMIC_HEIGHT = DYNAMIC_SIZE
DYNAMIC_WIDTH = DYNAMIC_SIZE

BLOCK_COUNT_HORIZONTAL = 17
BLOCK_COUNT_VERTICAL = 13

WINDOW_WIDTH = BLOCK_COUNT_HORIZONTAL * SPRITE_SIZE
WINDOW_HEIGHT = BLOCK_COUNT_VERTICAL * SPRITE_SIZE

GAME_SPEED = 60
GAME_CYCLE_SLEEP = 1000 / GAME_SPEED

UP = "up"
DOWN = "down"
LEFT = "left"
RIGHT = "right"

PLAYER_1 = 0
PLAYER_2 = 1
PLAYER_3 = 2
PLAYER_4 = 3

PLAYER_1_NAME = "pink"
PLAYER_2_NAME = "blue"
PLAYER_3_NAME = "green"
PLAYER_4_NAME = "yellow"

PLAYER_SPEED = 2
PLAYER_LIVES = 3
PLAYER_RESPAWN_TIME = 3 * GAME_SPEED
PLAYER_RESPAWN_TIME_STEP = 1

ENEMY_NAME = "enemy"
ENEMY_SPAWN = 100
ENEMY_SPEED = 1

BRICK_SPAWN = 100

EMPTY = 0
RESERVED = 1
GRASS = 2
WALL = 3
BRICK = 4
PLAYER = 5
ENEMY = 6
BOMB = 7

TEMPLATE_EMPTY = '/'
TEMPLATE_RESERVED = 'R'
TEMPLATE_WALL = 'W'
TEMPLATE_BRICK = 'B'
TEMPLATE_PLAYER = 'P'
TEMPLATE_ENEMY = 'E'
